### ISSUE TITLE
Bug updating state of select element

### ISSUE THREAD

**Issue by andrecasal** [brophdawg11/remix-validity-state#62]
When having two-way data binding, the select doesn't update on first try, only second.

Minimal reproduction on [StackBlitz](https://stackblitz.com/edit/remix-run-remix-qluwqf?file=app/routes/index.tsx)
```tsx
import { Link } from '@remix-run/react'
import type { ChangeEvent } from 'react'
import { useState } from 'react'
import { useValidatedSelect } from 'remix-validity-state'
import type { SelectDefinition } from 'remix-validity-state'

type FormSchema = {
	inputs: {
		select: SelectDefinition
	}
}

const formDefinition = {
	inputs: {
		select: {
			element: 'select',
			validationAttrs: {
				required: true,
			},
		},
	},
} satisfies FormSchema

export default function Index() {
	const options = [
		{ value: '', text: '--Choose an option--' },
		{ value: 'apple', text: 'Apple 🍏' },
		{ value: 'banana', text: 'Banana 🍌' },
		{ value: 'kiwi', text: 'Kiwi 🥝' },
	]

	const [value, setValue] = useState<string>(options[0].value)
	const select = useValidatedSelect({ name: 'select', formDefinition })
	const selectAttributes = select.getSelectAttrs()

	const onChange = (event: ChangeEvent<HTMLSelectElement>) => {
		console.log(event.target.value)
		setValue(event.target.value)
	}

	return (
		<form>
			<select {...selectAttributes} value={value} onChange={onChange}>
				{options.map((option) => (
					<option key={option.value} value={option.value}>
						{option.text}
					</option>
				))}
			</select>
		</form>
	)
}
```

**Comment by brophdawg11** [comment]
If you just need the value, you can access that via `useValidatedSelect().info.value` (added in `1.10.0` - #43).

2 way data binding probably won't play nice since there's already a `value`/`setValue` inside `useValidatedSelect` so I imagine your own `setValue` is blowing that away, and also not triggering updates internally since the library operates on `change` events so your external `setValue` is invisible to the internal state.  

It doesn't currently expose `setValue` but you can programmatically trigger new values with change events - see #39 for an example.

Is that sufficient for your use case?

**Comment by andrecasal** [comment]
Yeah, useValidatedSelect().info.value is enough 👍
