### ISSUE TITLE
Think about fields with multiple values

### ISSUE THREAD

**Issue by kentcdodds** [brophdawg11/remix-validity-state#8]
For example, this UI:

https://user-images.githubusercontent.com/1500684/189235897-6031cf36-bef7-43be-95c8-ef008cca84c5.mp4

Powered by this code: https://github.com/kentcdodds/fakebooks-remix/blob/15daa8e1c76a87df7f2af044d9b710d071c2a1f2/app/routes/__app/sales/invoices/new.tsx#L175-L203

And on the server that's validated like this: https://github.com/kentcdodds/fakebooks-remix/blob/15daa8e1c76a87df7f2af044d9b710d071c2a1f2/app/routes/__app/sales/invoices/new.tsx#L79-L93

I wonder how that would look with validity-state 🤔

**Comment by brophdawg11** [comment]
From a UI standpoint, this sort of "just works" since `useValidatedInput` is scoped to a given input, and IDs are now unique via `useId`.  I think where this will break at the moment is server-side validation since we're probably not doing anything with `formData.getAll` so we're probably only validating the last of each duplicate input.
